version: 2

jobs:
  build:
    docker:
      - image: novopl/python36:ci-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps-rev1-{{ checksum "requirements.txt" }}
      - restore_cache:
          key: tox-rev3-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}

      - run:
          name: Setup dependencies
          command: |
            which pip
            which python
            pip install -r requirements.txt
            pip install -r ops/devrequirements.txt
            peltak --help

      - run:
          name: Lint
          command: peltak lint

      - run:
          name: Test
          command: tox

      - save_cache:
          key: tox-rev3-{{ checksum "requirements.txt" }}-{{ checksum "ops/devrequirements.txt" }}
          paths:
          - .tox

      - run:
          name: Build Documentation
          command: |
            peltak docs --recreate --run-doctests
            mv docs/html docs/peltak-docs
            cd docs && zip -r ../.build/peltak-docs.zip peltak-docs

      - save_cache:
          key: deps-rev1-{{ checksum "requirements.txt" }}
          paths:
          - /usr/local/bin
          - /usr/local/lib/python3.6/site-packages
      - store_test_results:
          path: .build
      - store_artifacts:
          path: .build/coverage/
          destination: coverage
      - store_artifacts:
          path: .build/peltak-docs.zip

  release:
    docker:
      - image: novopl/python36:ci-alpine
    steps:
      - checkout
      - restore_cache:
          key: deps-rev1-{{ checksum "requirements.txt" }}
      - run: python setup.py develop
      - run: peltak pypi configure
      - run: peltak pypi upload
      - run: rm ~/.pypirc
      - run: peltak release tag
      - run: "git push origin v$(peltak version --porcelain)"


workflows:
  version: 2
  main:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
